apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: SYKEFRAVARSSTATISTIKK_API_BASE_URL
      value: https://sykefravarsstatistikk-api.dev-fss-pub.nais.io
    - name: IA_TJENESTER_METRIKKER_BASE_URL
      value: https://ia-tjenester-metrikker.dev.nav.no/ia-tjenester-metrikker
    - name: KURSOVERSIKT_BASE_URL
      value: https://kursoversikt.dev.nav.no/kursoversikt
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
      ## Next.js bruker NODE_ENV og forventer følgende verdier: 'production', 'development' eller 'test'
      ## Derfor overskriver vi NODE_ENV i dev-gcp og prod-gcp til 'production'
    - name: NODE_ENV
      value: production
    - name: SYKEFRAVARSSTATISTIKK_API_AUDIENCE
      value: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
    - name: IA_TJENESTER_METRIKKER_AUDIENCE
      value: "dev-gcp:arbeidsgiver:ia-tjenester-metrikker"
    - name: APP_INGRESS
      value: https://min-ia.dev.nav.no/min-ia
    - name: DECORATOR_ENV
      value: dev
    - name: DECORATOR_URL
      value: https://dekoratoren.dev.nav.no?context=arbeidsgiver
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://min-ia.dev.nav.no/min-ia
    - name: NEXT_PUBLIC_KALKULATOR_URL
      value: https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk/redirect-til-login?redirect=https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk/kalkulator
    - name: NEXT_PUBLIC_NETTKURS_URL
      value: https://arbeidsgiver-gcp.dev.nav.no/forebygge-sykefravaer/#webinar-og-kurs
    - name: NEXT_PUBLIC_SAMTALESTOTTE_URL
      value: https://arbeidsgiver-gcp.dev.nav.no/samtalestotte
    - name: NEXT_PUBLIC_SYKEFRAVARSSTATISTIKK_URL
      value: https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk/redirect-til-login?redirect=https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: /min-ia/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /min-ia/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://min-ia.dev.nav.no/min-ia
  prometheus:
    enabled: true
    path: /min-ia/internal/metrics
  accessPolicy:
    outbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: ia-tjenester-metrikker
          namespace: arbeidsgiver
          cluster: dev-gcp
      external:
        - host: dekoratoren.dev.nav.no
        - host: sykefravarsstatistikk-api.dev-fss-pub.nais.io
