apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3010
  env:
    - name: SYKEFRAVARSSTATISTIKK_API_BASE_URL
      value: https://sykefravarsstatistikk-api.dev-fss-pub.nais.io
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: https://loginservice.dev.nav.no/login?redirect=
    - name: NODE_ENV
      value: not-local
    - name: TOKENX_AUDIENCE
      value: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
    - name: APP_INGRESS
      value: https://min-ia.dev.nav.no/min-ia
    - name: DECORATOR_URL
      value: https://dekoratoren.dev.nav.no?context=arbeidsgiver
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: /min-ia/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /min-ia/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://min-ia.dev.nav.no/min-ia
  accessPolicy:
    outbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss
      external:
        - host: dekoratoren.dev.nav.no
        - host: sykefravarsstatistikk-api.dev-fss-pub.nais.io
        - host: loginservice.dev.nav.no
