apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: SYKEFRAVARSSTATISTIKK_API_BASE_URL
      value: https://sykefravarsstatistikk-api.dev-fss-pub.nais.io
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
      ## Next.js bruker NODE_ENV og forventer følgende verdier: 'production', 'development' eller 'test'
      ## Derfor overskriver vi NODE_ENV i dev-gcp og prod-gcp til 'production'
    - name: NODE_ENV
      value: production
    - name: TOKENX_AUDIENCE
      value: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
    - name: APP_INGRESS
      value: https://min-ia.dev.nav.no/min-ia
    - name: DECORATOR_URL
      value: https://dekoratoren.dev.nav.no?context=arbeidsgiver
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://min-ia.dev.nav.no/min-ia
    - name: SAMTALESTOTTE_URL
      value: https://arbeidsgiver-gcp.dev.nav.no/samtalestotte
    - name: NETTKURS
      value: https://arbeidsgiver-gcp.dev.nav.no/forebygge-sykefravaer/#webinar-og-kurs
    - name: SYKEFRAVARSSTATISTIKK
      value: https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk/success?redirect=https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk
    - name: KALKULATOR
      value: https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk/success?redirect=https://arbeidsgiver-gcp.dev.nav.no/sykefravarsstatistikk/kalkulator
    - name: IDEBANKEN
      value: https://www.idebanken.org
    - name: ARBEIDSMILJOPORTALEN
      value: https://www.arbeidsmiljoportalen.no
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: /min-ia/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /min-ia/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://min-ia.dev.nav.no/min-ia
  accessPolicy:
    outbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss
      external:
        - host: dekoratoren.dev.nav.no
        - host: sykefravarsstatistikk-api.dev-fss-pub.nais.io
