apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia-mock
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: ARBEIDSGIVER_HOSTNAME
      value: arbeidsgiver.nav.no
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: NODE_ENV
      value: development
    - name: APP_INGRESS
      value: https://arbeidsgiver.ekstern.dev.nav.no/forebygge-fravar
    - name: DECORATOR_ENV
      value: dev
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/forebygge-fravar
    - name: SAMTALESTOTTE_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/samtalestotte
    - name: SYKEFRAVARSSTATISTIKK_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/sykefravarsstatistikk
    - name: FOREBYGGINGSPLAN_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/forebyggingsplan
    - name: MIN_SIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.ekstern.dev.nav.no/min-side-arbeidsgiver
    - name: KONTAKT_OSS_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/kontakt-oss
    - name: FIA_ARBEIDSGIVER_HOSTNAME
      value: arbeidsgiver.ekstern.dev.nav.no
  tokenx:
    enabled: true
  idporten:
    enabled: false
  liveness:
    path: /forebygge-fravar/api/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /forebygge-fravar/api/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://arbeidsgiver.ekstern.dev.nav.no/forebygge-fravar
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.ekstern.dev.nav.no