apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: KURSOVERSIKT_BASE_URL
      value: https://arbeidsgiver.nav.no/kursoversikt
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
      ## Next.js bruker NODE_ENV og forventer følgende verdier: 'production', 'development' eller 'test'
      ## Derfor overskriver vi NODE_ENV i labs-gcp 'development'
    - name: NODE_ENV
      value: development
    - name: APP_INGRESS
      value: https://arbeidsgiver.labs.nais.io/min-ia
    - name: DECORATOR_ENV
      value: prod
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren/?context=arbeidsgiver
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://arbeidsgiver.nav.no/min-ia
    - name: NEXT_PUBLIC_KALKULATOR_URL
      value: https://arbeidsgiver.labs.nais.io/min-ia/kalkulator
    - name: NEXT_PUBLIC_NETTKURS_URL
      value: https://arbeidsgiver.nav.no/forebygge-sykefravaer/#webinar-og-kurs
    - name: NEXT_PUBLIC_SAMTALESTOTTE_URL
      value: https://arbeidsgiver.labs.nais.io/samtalestotte
    - name: NEXT_PUBLIC_SYKEFRAVARSSTATISTIKK_URL
      value: https://arbeidsgiver.labs.nais.io/sykefravarsstatistikk
  liveness:
    path: /min-ia/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /min-ia/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://arbeidsgiver.labs.nais.io/min-ia
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
