apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: KURSOVERSIKT_BASE_URL
      value: https://arbeidsgiver.nav.no/kursoversikt
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
      ## Next.js bruker NODE_ENV og forventer følgende verdier: 'production', 'development' eller 'test'
      ## Derfor overskriver vi NODE_ENV i labs-gcp 'development'
    - name: NODE_ENV
      value: development
    - name: APP_INGRESS
      value: https://arbeidsgiver.labs.nais.io/forebygge-fravar
    - name: DECORATOR_ENV
      value: prod
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren/?context=arbeidsgiver
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://arbeidsgiver.nav.no/forebygge-fravar

    - name: NEXT_PUBLIC__ENVIRONMENT_IS_PRODUCTION
      value: false
    - name: NEXT_PUBLIC__SAMTALESTOTTE_URL
      value: https://arbeidsgiver.labs.nais.io/samtalestotte
    - name: NEXT_PUBLIC__SYKEFRAVARSSTATISTIKK_URL
      value: https://arbeidsgiver.labs.nais.io/sykefravarsstatistikk
    - name: NEXT_PUBLIC__FOREBYGGINGSPLAN_URL
      value: https://arbeidsgiver.labs.nais.io/forebyggingsplan
    - name: NEXT_PUBLIC__MIN_SIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.labs.nais.io/min-side-arbeidsgiver
  liveness:
    path: /forebygge-fravar/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /forebygge-fravar/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://arbeidsgiver.labs.nais.io/forebygge-fravar
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
