apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3010
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: NODE_ENV
      value: labs
  liveness:
    path: /min-ia/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /min-ia/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://arbeidsgiver.labs.nais.io/min-ia
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
