apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: SYKEFRAVARSSTATISTIKK_API_BASE_URL
      value: https://sykefravarsstatistikk-api.prod-fss-pub.nais.io
    - name: IA_TJENESTER_METRIKKER_BASE_URL
      value: https://arbeidsgiver.nav.no/ia-tjenester-metrikker
    - name: KURSOVERSIKT_BASE_URL
      value: https://arbeidsgiver.nav.no/kursoversikt
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
      ## Next.js bruker NODE_ENV og forventer følgende verdier: 'production', 'development' eller 'test'
      ## Derfor overskriver vi NODE_ENV i dev-gcp og prod-gcp til 'production'
    - name: NODE_ENV
      value: production
    - name: SYKEFRAVARSSTATISTIKK_API_AUDIENCE
      value: "prod-fss:arbeidsgiver:sykefravarsstatistikk-api"
    - name: IA_TJENESTER_METRIKKER_AUDIENCE
      value: "prod-gcp:arbeidsgiver:ia-tjenester-metrikker"
    - name: NOTIFIKASJON_API_AUDIENCE
      value: "prod-gcp:fager:notifikasjon-bruker-api"
    - name: APP_INGRESS
      value: https://arbeidsgiver.nav.no/forebygge-fravar
    - name: DECORATOR_ENV
      value: prod
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren?context=arbeidsgiver
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://arbeidsgiver.nav.no/forebygge-fravar

    - name: ENVIRONMENT
      value: prod
    - name: SAMTALESTOTTE_URL
      value: https://arbeidsgiver.nav.no/samtalestotte
    - name: SYKEFRAVARSSTATISTIKK_URL
      value: https://arbeidsgiver.nav.no/sykefravarsstatistikk
    - name: FOREBYGGINGSPLAN_URL
      value: https://arbeidsgiver.nav.no/forebyggingsplan
    - name: MIN_SIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: /forebygge-fravar/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /forebygge-fravar/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://arbeidsgiver.nav.no/forebygge-fravar
  prometheus:
    enabled: true
    path: /forebygge-fravar/internal/metrics
  accessPolicy:
    outbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: prod-fss
        - application: ia-tjenester-metrikker
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: notifikasjon-bruker-api
          namespace: fager
      external:
        - host: dekoratoren.nav.no
        - host: sykefravarsstatistikk-api.prod-fss-pub.nais.io
