apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-ia
  namespace: teamia
  labels:
    team: teamia
spec:
  image: {{image}}
  port: 3000
  env:
    - name: SYKEFRAVARSSTATISTIKK_API_HOSTNAME
      value: sykefravarsstatistikk-api.prod-fss-pub.nais.io
    - name: FOREBYGGINGSPLAN_API_BASEURL
      value: forebyggingsplan.teamia.svc.cluster.local
    - name: FOREBYGGINGSPLAN_API_AUDIENCE
      value: prod-gcp:teamia:forebyggingsplan
    - name: IA_TJENESTER_METRIKKER_HOSTNAME
      value: arbeidsgiver.nav.no
    - name: ARBEIDSGIVER_HOSTNAME
      value: arbeidsgiver.nav.no
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
      ## Next.js bruker NODE_ENV og forventer følgende verdier: 'production', 'development' eller 'test'
      ## Derfor overskriver vi NODE_ENV i dev-gcp og prod-gcp til 'production'
    - name: NODE_ENV
      value: production
    - name: SYKEFRAVARSSTATISTIKK_API_AUDIENCE
      value: "prod-fss:arbeidsgiver:sykefravarsstatistikk-api"
    - name: FIA_ARBEIDSGIVER_AUDIENCE
      value: "prod-gcp:pia:fia-arbeidsgiver"
    - name: IA_TJENESTER_METRIKKER_AUDIENCE
      value: "prod-gcp:arbeidsgiver:ia-tjenester-metrikker"
    - name: NOTIFIKASJON_API_AUDIENCE
      value: "prod-gcp:fager:notifikasjon-bruker-api"
    - name: APP_INGRESS
      value: https://arbeidsgiver.nav.no/forebygge-fravar
    - name: DECORATOR_ENV
      value: prod
    - name: DECORATOR_BREADCRUMB_THIS_PAGE_URL
      value: https://arbeidsgiver.nav.no/forebygge-fravar
    - name: FIA_ARBEIDSGIVER_HOSTNAME
      value: fia-arbeidsgiver.pia
    - name: SAMTALESTOTTE_URL
      value: https://arbeidsgiver.nav.no/samtalestotte
    - name: SYKEFRAVARSSTATISTIKK_URL
      value: https://arbeidsgiver.nav.no/forebygge-fravar/sykefravarsstatistikk
    - name: FOREBYGGINGSPLAN_URL
      value: https://arbeidsgiver.nav.no/forebyggingsplan
    - name: MIN_SIDE_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver
    - name: KONTAKT_OSS_ARBEIDSGIVER_URL
      value: https://arbeidsgiver.nav.no/kontakt-oss
    - name: GRAFANA_AGENT_COLLECTOR_URL
      value: https://telemetry.nav.no/collect
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false
  liveness:
    path: /forebygge-fravar/api/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /forebygge-fravar/api/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - https://arbeidsgiver.nav.no/forebygge-fravar
  prometheus:
    enabled: true
    path: /forebygge-fravar/internal/metrics
  accessPolicy:
    outbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: prod-fss
        - application: ia-tjenester-metrikker
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: notifikasjon-bruker-api
          namespace: fager
        - application: nav-dekoratoren
          namespace: personbruker
        - application: fia-arbeidsgiver
          namespace: pia
      external:
        - host: www.nav.no
        - host: arbeidsgiver.nav.no
        - host: sykefravarsstatistikk-api.prod-fss-pub.nais.io
