apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx:ingress:kubernetes:io/rewrite-target: "https://forebygge-fravar.dev.nav.no/forebygge-fravar/$2"
    prometheus.io/scrape: "false"
  labels:
    app: min-ia
    team: teamia
  name: min-ia-redirect
  namespace: teamia
spec:
  ingressClassName: gw-ekstern-dev-nav-no
  rules:
    - host: min-ia.dev.nav.no
      http:
        paths:
          - backend:
              service:
                name: min-ia
                port:
                  number: 80
            path: /min-ia(/|$)(.*)
            pathType: ImplementationSpecific