export const altinn3Organisasjoner = [
  {
    orgnr: "311111111",
    altinn3Tilganger: [
      "nav_forebygge-og-redusere-sykefravar_ia-samarbeid",
      "nav_forebygge-og-redusere-sykefravar_sykefravarsstatistikk",
      "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger",
      "nav_sosialtjenester_digisos-avtale",
      "nav_utbetaling_endre-kontonummer-refusjon-arbeidsgiver",
      "nav_arbeidsforhold_aa-registeret-innsyn-arbeidsgiver",
      "nav_arbeidsforhold_aa-registeret-brukerstotte",
      "nav_arbeidsforhold_aa-registeret-sok-tilgang",
      "nav_tiltak_tiltaksrefusjon",
      "nav_foreldrepenger_inntektsmelding",
      "nav_rekruttering_stillingsannonser",
    ],
    altinn2Tilganger: [
      "5934:1",
      "3403:1",
      "5810:1",
      "5867:1",
      "2896:87",
      "5441:1",
      "5441:2",
      "5719:1",
      "5078:1",
      "4826:1",
      "4936:1",
      "5278:1",
      "5332:1",
      "5384:1",
      "5516:1",
      "5516:2",
      "5516:3",
      "5516:4",
      "5516:5",
      "5516:6",
      "5902:1",
    ],
    underenheter: [
      {
        orgnr: "999999997",
        altinn3Tilganger: [
          "nav_forebygge-og-redusere-sykefravar_ia-samarbeid",
          "nav_forebygge-og-redusere-sykefravar_sykefravarsstatistikk",
          "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger",
          "nav_sosialtjenester_digisos-avtale",
          "nav_utbetaling_endre-kontonummer-refusjon-arbeidsgiver",
          "nav_arbeidsforhold_aa-registeret-innsyn-arbeidsgiver",
          "nav_arbeidsforhold_aa-registeret-brukerstotte",
          "nav_arbeidsforhold_aa-registeret-sok-tilgang",
          "nav_tiltak_tiltaksrefusjon",
          "nav_foreldrepenger_inntektsmelding",
          "nav_rekruttering_stillingsannonser",
        ],
        altinn2Tilganger: [
          "5934:1",
          "3403:1",
          "5810:1",
          "5867:1",
          "2896:87",
          "5441:1",
          "5441:2",
          "5719:1",
          "5078:1",
          "4826:1",
          "4936:1",
          "5278:1",
          "5332:1",
          "5384:1",
          "5516:1",
          "5516:2",
          "5516:3",
          "5516:4",
          "5516:5",
          "5516:6",
          "5902:1",
        ],
        underenheter: [],
        navn: "Generell feil",
        organisasjonsform: "BEDR",
      },
      {
        orgnr: "999999996",
        altinn3Tilganger: [
          "nav_forebygge-og-redusere-sykefravar_ia-samarbeid",
          "nav_forebygge-og-redusere-sykefravar_sykefravarsstatistikk",
          "nav_permittering-og-nedbemmaning_innsyn-i-alle-innsendte-meldinger",
          "nav_sosialtjenester_digisos-avtale",
          "nav_utbetaling_endre-kontonummer-refusjon-arbeidsgiver",
          "nav_arbeidsforhold_aa-registeret-innsyn-arbeidsgiver",
          "nav_arbeidsforhold_aa-registeret-brukerstotte",
          "nav_arbeidsforhold_aa-registeret-sok-tilgang",
          "nav_tiltak_tiltaksrefusjon",
          "nav_foreldrepenger_inntektsmelding",
          "nav_rekruttering_stillingsannonser",
        ],
        altinn2Tilganger: [
          "5934:1",
          "3403:1",
          "5810:1",
          "5867:1",
          "2896:87",
          "5441:1",
          "5441:2",
          "5719:1",
          "5078:1",
          "4826:1",
          "4936:1",
          "5278:1",
          "5332:1",
          "5384:1",
          "5516:1",
          "5516:2",
          "5516:3",
          "5516:4",
          "5516:5",
          "5516:6",
          "5902:1",
        ],
        underenheter: [],
        navn: "Mangler tilgang",
        organisasjonsform: "BEDR",
      },
    ],
    navn: "System feil AS",
    organisasjonsform: "AS",
  },
  {
    orgnr: "211111111",
    altinn3Tilganger: [
      "nav_forebygge-og-redusere-sykefravar_ia-samarbeid",
      "nav_tiltak_tiltaksrefusjon",
      "nav_foreldrepenger_inntektsmelding",
      "nav_rekruttering_stillingsannonser",
    ],
    altinn2Tilganger: ["5934:1", "5078:1", "4826:1", "4936:1", "5902:1"],
    underenheter: [
      {
        orgnr: "810969439",
        altinn3Tilganger: [
          "nav_forebygge-og-redusere-sykefravar_ia-samarbeid",
          "nav_tiltak_tiltaksrefusjon",
          "nav_foreldrepenger_inntektsmelding",
          "nav_rekruttering_stillingsannonser",
        ],
        altinn2Tilganger: ["5934:1", "5078:1", "4826:1", "4936:1", "5902:1"],
        underenheter: [],
        navn: "Trøndelag Tømmerere avd. OSLO [Local server]",
        organisasjonsform: "BEDR",
      },
    ],
    navn: "Trøndelag Tømmerere [Local server]",
    organisasjonsform: "AS",
  },
  {
    orgnr: "310807176",
    altinn3Tilganger: [
      "nav_forebygge-og-redusere-sykefravar_sykefravarsstatistikk",
    ],
    altinn2Tilganger: ["3403:1"],
    underenheter: [],
    navn: "UVITENDE SNILL TIGER AS",
    organisasjonsform: "AS",
  },
  {
    orgnr: "111111111",
    altinn3Tilganger: ["nav_forebygge-og-redusere-sykefravar_ia-samarbeid"],
    altinn2Tilganger: ["5934:1"],
    underenheter: [
      {
        orgnr: "910969439",
        altinn3Tilganger: ["nav_forebygge-og-redusere-sykefravar_ia-samarbeid"],
        altinn2Tilganger: ["5934:1"],
        underenheter: [],
        navn: "FIKTIVT SYKEHUS [TEST]",
        organisasjonsform: "BEDR",
      },
    ],
    navn: "FIKTIVT SYKEHUS [TEST]",
    organisasjonsform: "AS",
  },
  {
    orgnr: "910969439",
    altinn3Tilganger: ["nav_forebygge-og-redusere-sykefravar_ia-samarbeid"],
    altinn2Tilganger: ["5934:1"],
    underenheter: [
      {
        orgnr: "910969440",
        altinn3Tilganger: ["nav_forebygge-og-redusere-sykefravar_ia-samarbeid"],
        altinn2Tilganger: ["5934:1"],
        underenheter: [],
        navn: "HEI OG HÅ BARNEHAGE OSLO [Local server]",
        organisasjonsform: "BEDR",
      },
    ],
    navn: "HEI OG HÅ BARNEHAGE",
    organisasjonsform: "AS",
  },
];
