export const kvartalsvisHistorikkMockdata = [
  {
    type: "LAND",
    label: "Norge",
    kvartalsvisSykefraværsprosent: [
      {
        årstall: 2015,
        kvartal: 2,
        erMaskert: false,
        prosent: 5.5,
        tapteDagsverk: 55,
        muligeDagsverk: 5500,
      },
      {
        årstall: 2015,
        kvartal: 3,
        erMaskert: false,
        prosent: 6,
        tapteDagsverk: 60,
        muligeDagsverk: 6000,
      },
      {
        årstall: 2015,
        kvartal: 4,
        erMaskert: false,
        prosent: 6.8,
        tapteDagsverk: 68,
        muligeDagsverk: 6800,
      },
      {
        årstall: 2016,
        kvartal: 1,
        erMaskert: false,
        prosent: 6.4,
        tapteDagsverk: 64,
        muligeDagsverk: 6400,
      },
      {
        årstall: 2016,
        kvartal: 2,
        erMaskert: false,
        prosent: 5.6,
        tapteDagsverk: 56,
        muligeDagsverk: 5600,
      },
      {
        årstall: 2016,
        kvartal: 3,
        erMaskert: false,
        prosent: 6.1,
        tapteDagsverk: 61,
        muligeDagsverk: 6100,
      },
      {
        årstall: 2016,
        kvartal: 4,
        erMaskert: false,
        prosent: 7.1,
        tapteDagsverk: 71,
        muligeDagsverk: 7100,
      },
      {
        årstall: 2017,
        kvartal: 1,
        erMaskert: false,
        prosent: 6.7,
        tapteDagsverk: 67,
        muligeDagsverk: 6700,
      },
      {
        årstall: 2017,
        kvartal: 2,
        erMaskert: false,
        prosent: 5.8,
        tapteDagsverk: 58,
        muligeDagsverk: 5800,
      },
      {
        årstall: 2017,
        kvartal: 3,
        erMaskert: false,
        prosent: 6.3,
        tapteDagsverk: 63,
        muligeDagsverk: 6300,
      },
      {
        årstall: 2017,
        kvartal: 4,
        erMaskert: false,
        prosent: 7.2,
        tapteDagsverk: 72,
        muligeDagsverk: 7200,
      },
      {
        årstall: 2018,
        kvartal: 1,
        erMaskert: false,
        prosent: 6.7,
        tapteDagsverk: 67,
        muligeDagsverk: 6700,
      },
      {
        årstall: 2018,
        kvartal: 2,
        erMaskert: false,
        prosent: 5.8,
        tapteDagsverk: 58,
        muligeDagsverk: 5800,
      },
      {
        årstall: 2018,
        kvartal: 3,
        erMaskert: false,
        prosent: 6.2,
        tapteDagsverk: 62,
        muligeDagsverk: 6200,
      },
      {
        årstall: 2018,
        kvartal: 4,
        erMaskert: false,
        prosent: 7,
        tapteDagsverk: 70,
        muligeDagsverk: 7000,
      },
      {
        årstall: 2019,
        kvartal: 1,
        erMaskert: false,
        prosent: 6.5,
        tapteDagsverk: 65,
        muligeDagsverk: 6500,
      },
      {
        årstall: 2019,
        kvartal: 2,
        erMaskert: false,
        prosent: 5.6,
        tapteDagsverk: 56,
        muligeDagsverk: 5600,
      },
      {
        årstall: 2019,
        kvartal: 3,
        erMaskert: false,
        prosent: 6.1,
        tapteDagsverk: 61,
        muligeDagsverk: 6100,
      },
      {
        årstall: 2019,
        kvartal: 4,
        erMaskert: false,
        prosent: 7,
        tapteDagsverk: 70,
        muligeDagsverk: 7000,
      },
      {
        årstall: 2020,
        kvartal: 1,
        erMaskert: false,
        prosent: 6.4,
        tapteDagsverk: 64,
        muligeDagsverk: 6400,
      },
    ],
  },
  {
    type: "SEKTOR",
    label: "Statlig forvaltning",
    kvartalsvisSykefraværsprosent: [
      {
        årstall: 2015,
        kvartal: 2,
        erMaskert: false,
        prosent: 4,
        tapteDagsverk: 40,
        muligeDagsverk: 4000,
      },
      {
        årstall: 2015,
        kvartal: 3,
        erMaskert: false,
        prosent: 4.9,
        tapteDagsverk: 49,
        muligeDagsverk: 4900,
      },
      {
        årstall: 2015,
        kvartal: 4,
        erMaskert: false,
        prosent: 6.8,
        tapteDagsverk: 68,
        muligeDagsverk: 6800,
      },
      {
        årstall: 2016,
        kvartal: 1,
        erMaskert: false,
        prosent: 5.8,
        tapteDagsverk: 58,
        muligeDagsverk: 5800,
      },
      {
        årstall: 2016,
        kvartal: 2,
        erMaskert: false,
        prosent: 4.1,
        tapteDagsverk: 41,
        muligeDagsverk: 4100,
      },
      {
        årstall: 2016,
        kvartal: 3,
        erMaskert: false,
        prosent: 5,
        tapteDagsverk: 50,
        muligeDagsverk: 5000,
      },
      {
        årstall: 2016,
        kvartal: 4,
        erMaskert: false,
        prosent: 6.6,
        tapteDagsverk: 66,
        muligeDagsverk: 6600,
      },
      {
        årstall: 2017,
        kvartal: 1,
        erMaskert: false,
        prosent: 5.7,
        tapteDagsverk: 57,
        muligeDagsverk: 5700,
      },
      {
        årstall: 2017,
        kvartal: 2,
        erMaskert: false,
        prosent: 4.1,
        tapteDagsverk: 41,
        muligeDagsverk: 4100,
      },
      {
        årstall: 2017,
        kvartal: 3,
        erMaskert: false,
        prosent: 5.1,
        tapteDagsverk: 51,
        muligeDagsverk: 5100,
      },
      {
        årstall: 2017,
        kvartal: 4,
        erMaskert: false,
        prosent: 6.7,
        tapteDagsverk: 67,
        muligeDagsverk: 6700,
      },
      {
        årstall: 2018,
        kvartal: 1,
        erMaskert: false,
        prosent: 5.7,
        tapteDagsverk: 57,
        muligeDagsverk: 5700,
      },
      {
        årstall: 2018,
        kvartal: 2,
        erMaskert: false,
        prosent: 4.1,
        tapteDagsverk: 41,
        muligeDagsverk: 4100,
      },
      {
        årstall: 2018,
        kvartal: 3,
        erMaskert: false,
        prosent: 5.1,
        tapteDagsverk: 51,
        muligeDagsverk: 5100,
      },
      {
        årstall: 2018,
        kvartal: 4,
        erMaskert: false,
        prosent: 6.9,
        tapteDagsverk: 69,
        muligeDagsverk: 6900,
      },
      {
        årstall: 2019,
        kvartal: 1,
        erMaskert: false,
        prosent: 6.1,
        tapteDagsverk: 61,
        muligeDagsverk: 6100,
      },
      {
        årstall: 2019,
        kvartal: 2,
        erMaskert: false,
        prosent: 4.2,
        tapteDagsverk: 42,
        muligeDagsverk: 4200,
      },
      {
        årstall: 2019,
        kvartal: 3,
        erMaskert: false,
        prosent: 5.2,
        tapteDagsverk: 52,
        muligeDagsverk: 5200,
      },
      {
        årstall: 2019,
        kvartal: 4,
        erMaskert: false,
        prosent: 6.8,
        tapteDagsverk: 68,
        muligeDagsverk: 6800,
      },
      {
        årstall: 2020,
        kvartal: 1,
        erMaskert: false,
        prosent: 5.9,
        tapteDagsverk: 59,
        muligeDagsverk: 5900,
      },
    ],
  },
  {
    type: "VIRKSOMHET",
    label: "Dette er en virksomhet",
    kvartalsvisSykefraværsprosent: [
      {
        årstall: 2015,
        kvartal: 2,
        erMaskert: false,
        prosent: 4,
        tapteDagsverk: 40,
        muligeDagsverk: 4000,
      },
      {
        årstall: 2015,
        kvartal: 3,
        erMaskert: false,
        prosent: 6,
        tapteDagsverk: 60,
        muligeDagsverk: 6000,
      },
      {
        årstall: 2015,
        kvartal: 4,
        erMaskert: false,
        prosent: 8.8,
        tapteDagsverk: 88,
        muligeDagsverk: 8800,
      },
      {
        årstall: 2016,
        kvartal: 1,
        erMaskert: false,
        prosent: 8.7,
        tapteDagsverk: 87,
        muligeDagsverk: 8700,
      },
      {
        årstall: 2016,
        kvartal: 2,
        erMaskert: false,
        prosent: 7.9,
        tapteDagsverk: 79,
        muligeDagsverk: 7900,
      },
      {
        årstall: 2016,
        kvartal: 3,
        erMaskert: false,
        prosent: 9.8,
        tapteDagsverk: 98,
        muligeDagsverk: 9800,
      },
      {
        årstall: 2016,
        kvartal: 4,
        erMaskert: false,
        prosent: 12.6,
        tapteDagsverk: 126,
        muligeDagsverk: 12600,
      },
      {
        årstall: 2017,
        kvartal: 1,
        erMaskert: false,
        prosent: 12.5,
        tapteDagsverk: 125,
        muligeDagsverk: 12500,
      },
      {
        årstall: 2017,
        kvartal: 2,
        erMaskert: false,
        prosent: 11.7,
        tapteDagsverk: 117,
        muligeDagsverk: 11700,
      },
      {
        årstall: 2017,
        kvartal: 3,
        erMaskert: false,
        prosent: 13.6,
        tapteDagsverk: 136,
        muligeDagsverk: 13600,
      },
      {
        årstall: 2017,
        kvartal: 4,
        erMaskert: false,
        prosent: 16.5,
        tapteDagsverk: 165,
        muligeDagsverk: 16500,
      },
      {
        årstall: 2018,
        kvartal: 1,
        erMaskert: false,
        prosent: 16.5,
        tapteDagsverk: 165,
        muligeDagsverk: 16500,
      },
      {
        årstall: 2018,
        kvartal: 2,
        erMaskert: false,
        prosent: 15.9,
        tapteDagsverk: 159,
        muligeDagsverk: 15900,
      },
      {
        årstall: 2018,
        kvartal: 3,
        erMaskert: false,
        prosent: 18,
        tapteDagsverk: 180,
        muligeDagsverk: 18000,
      },
      {
        årstall: 2018,
        kvartal: 4,
        erMaskert: false,
        prosent: 20.6,
        tapteDagsverk: 206,
        muligeDagsverk: 20600,
      },
      {
        årstall: 2019,
        kvartal: 1,
        erMaskert: false,
        prosent: 20.5,
        tapteDagsverk: 205,
        muligeDagsverk: 20500,
      },
      {
        årstall: 2019,
        kvartal: 2,
        erMaskert: false,
        prosent: 19.6,
        tapteDagsverk: 196,
        muligeDagsverk: 19600,
      },
      {
        årstall: 2019,
        kvartal: 3,
        erMaskert: false,
        prosent: 21.5,
        tapteDagsverk: 215,
        muligeDagsverk: 21500,
      },
      {
        årstall: 2019,
        kvartal: 4,
        erMaskert: false,
        prosent: 24.1,
        tapteDagsverk: 241,
        muligeDagsverk: 24100,
      },
      {
        årstall: 2020,
        kvartal: 1,
        erMaskert: false,
        prosent: 24,
        tapteDagsverk: 240,
        muligeDagsverk: 24000,
      },
    ],
  },
  {
    type: "OVERORDNET_ENHET",
    label: "Dette er en overordnet virksomhet",
    kvartalsvisSykefraværsprosent: [
      {
        årstall: 2015,
        kvartal: 2,
        erMaskert: false,
        prosent: 3,
        tapteDagsverk: 30,
        muligeDagsverk: 3000,
      },
      {
        årstall: 2015,
        kvartal: 3,
        erMaskert: false,
        prosent: 5.9,
        tapteDagsverk: 59,
        muligeDagsverk: 5900,
      },
      {
        årstall: 2015,
        kvartal: 4,
        erMaskert: false,
        prosent: 11.4,
        tapteDagsverk: 114,
        muligeDagsverk: 11400,
      },
      {
        årstall: 2016,
        kvartal: 1,
        erMaskert: false,
        prosent: 8.5,
        tapteDagsverk: 85,
        muligeDagsverk: 8500,
      },
      {
        årstall: 2016,
        kvartal: 2,
        erMaskert: false,
        prosent: 2.8,
        tapteDagsverk: 28,
        muligeDagsverk: 2800,
      },
      {
        årstall: 2016,
        kvartal: 3,
        erMaskert: false,
        prosent: 5.7,
        tapteDagsverk: 57,
        muligeDagsverk: 5700,
      },
      {
        årstall: 2016,
        kvartal: 4,
        erMaskert: false,
        prosent: 11.1,
        tapteDagsverk: 111,
        muligeDagsverk: 11100,
      },
      {
        årstall: 2017,
        kvartal: 1,
        erMaskert: false,
        prosent: 8.6,
        tapteDagsverk: 86,
        muligeDagsverk: 8600,
      },
      {
        årstall: 2017,
        kvartal: 2,
        erMaskert: false,
        prosent: 3,
        tapteDagsverk: 30,
        muligeDagsverk: 3000,
      },
      {
        årstall: 2017,
        kvartal: 3,
        erMaskert: false,
        prosent: 6.1,
        tapteDagsverk: 61,
        muligeDagsverk: 6100,
      },
      {
        årstall: 2017,
        kvartal: 4,
        erMaskert: false,
        prosent: 11,
        tapteDagsverk: 110,
        muligeDagsverk: 11000,
      },
      {
        årstall: 2018,
        kvartal: 1,
        erMaskert: false,
        prosent: 7.8,
        tapteDagsverk: 78,
        muligeDagsverk: 7800,
      },
    ],
  },
  {
    type: "BRANSJE",
    label: "Dette er en bransje",
    kvartalsvisSykefraværsprosent: [
      {
        årstall: 2015,
        kvartal: 2,
        erMaskert: false,
        prosent: 7,
        tapteDagsverk: 70,
        muligeDagsverk: 7000,
      },
      {
        årstall: 2015,
        kvartal: 3,
        erMaskert: false,
        prosent: 7,
        tapteDagsverk: 70,
        muligeDagsverk: 7000,
      },
      {
        årstall: 2015,
        kvartal: 4,
        erMaskert: false,
        prosent: 7.8,
        tapteDagsverk: 78,
        muligeDagsverk: 7800,
      },
      {
        årstall: 2016,
        kvartal: 1,
        erMaskert: false,
        prosent: 7.7,
        tapteDagsverk: 77,
        muligeDagsverk: 7700,
      },
      {
        årstall: 2016,
        kvartal: 2,
        erMaskert: false,
        prosent: 6.8,
        tapteDagsverk: 68,
        muligeDagsverk: 6800,
      },
      {
        årstall: 2016,
        kvartal: 3,
        erMaskert: false,
        prosent: 7.7,
        tapteDagsverk: 77,
        muligeDagsverk: 7700,
      },
      {
        årstall: 2016,
        kvartal: 4,
        erMaskert: false,
        prosent: 8.8,
        tapteDagsverk: 88,
        muligeDagsverk: 8800,
      },
      {
        årstall: 2017,
        kvartal: 1,
        erMaskert: false,
        prosent: 8.6,
        tapteDagsverk: 86,
        muligeDagsverk: 8600,
      },
      {
        årstall: 2017,
        kvartal: 2,
        erMaskert: false,
        prosent: 7.9,
        tapteDagsverk: 79,
        muligeDagsverk: 7900,
      },
      {
        årstall: 2017,
        kvartal: 3,
        erMaskert: false,
        prosent: 8.2,
        tapteDagsverk: 82,
        muligeDagsverk: 8200,
      },
      {
        årstall: 2017,
        kvartal: 4,
        erMaskert: false,
        prosent: 9.1,
        tapteDagsverk: 91,
        muligeDagsverk: 9100,
      },
      {
        årstall: 2018,
        kvartal: 1,
        erMaskert: false,
        prosent: 8.2,
        tapteDagsverk: 82,
        muligeDagsverk: 8200,
      },
      {
        årstall: 2018,
        kvartal: 2,
        erMaskert: false,
        prosent: 7.5,
        tapteDagsverk: 75,
        muligeDagsverk: 7500,
      },
      {
        årstall: 2018,
        kvartal: 3,
        erMaskert: false,
        prosent: 8.3,
        tapteDagsverk: 83,
        muligeDagsverk: 8300,
      },
      {
        årstall: 2018,
        kvartal: 4,
        erMaskert: false,
        prosent: 9.5,
        tapteDagsverk: 95,
        muligeDagsverk: 9500,
      },
      {
        årstall: 2019,
        kvartal: 1,
        erMaskert: false,
        prosent: 9.2,
        tapteDagsverk: 92,
        muligeDagsverk: 9200,
      },
      {
        årstall: 2019,
        kvartal: 2,
        erMaskert: false,
        prosent: 8.7,
        tapteDagsverk: 87,
        muligeDagsverk: 8700,
      },
      {
        årstall: 2019,
        kvartal: 3,
        erMaskert: false,
        prosent: 9,
        tapteDagsverk: 90,
        muligeDagsverk: 9000,
      },
      {
        årstall: 2019,
        kvartal: 4,
        erMaskert: false,
        prosent: 9.6,
        tapteDagsverk: 96,
        muligeDagsverk: 9600,
      },
      {
        årstall: 2020,
        kvartal: 1,
        erMaskert: false,
        prosent: 9.3,
        tapteDagsverk: 93,
        muligeDagsverk: 9300,
      },
      {
        årstall: 2020,
        kvartal: 2,
        erMaskert: false,
        prosent: 8.1,
        tapteDagsverk: 81,
        muligeDagsverk: 8100,
      },
    ],
  },
];
